services:
  app:
    build:
      context: ./php
    container_name: laravel_app
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "sleep 15 && composer install && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  db_data: